### PR TITLE
add wireframe

### PR DESCRIPTION
**Pull request by andrewmar**

### CODE REVIEW

**Review by HannahBurks — CHANGES_REQUESTED** [review]
A really nice start Andrew 👍🏼 

A few amendments to be made:
- What component is the log in page ‘/‘? - add this to your component tree
- Thinking about state - if the articles rendered is dependant on the topic selected, where do you think the state needs to be in order for the articles to have access to the selected topic?
- Think about what api end points we are going to use and where. 
- What routes contain which components

Once the above changes have been made, please send another pull request

**Review by HannahBurks — CHANGES_REQUESTED** [review]
We are also going to need a state to handle the votes if we add a vote - this would need to be optimistically rendered on the single article page :)

**Comment by HannahBurks** [comment]
Almost there, please make the above amendment and then send another pr :)

**Comment by aloush-dev** [comment]
All good!

**Review by aloush-dev — APPROVED** [review]

**Pull request merged**
